
# Font settings
font_family JetBrainsMono
font_size 12.0

# Window opacity
background_opacity 0.9

# Window padding
padding_width 15
padding_height 15

# Selection settings
copy_on_select yes


allow_bold yes
allow_italic yes


# # Colors
# foreground #fcfcfc
# background #000000
#
#  Normal colors
# color0 #000000
# color1 #de5d68
# color2 #8fb573
# color3 #dbb671
# color4 #57a5e5
# color5 #bb70d2
# color6 #51a8b3
# color7 #bbbbbb

# Bright colors
#color8 #555555
#color9 #ff5555
#color10 #50fa7b
#color11 #f1fa8c
#color12 #caa9fa
#color13 #ff79c6
#color14 #8be9fd
#color15 #ffffff

scrollback_lines 2000
scrollback_pager-history_size 0 
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 5.0
url_color #4287f5 
url_style curly
open_url_modifiers none
open_url_with default
url_prefixes http https file ftp git

