/* eslint-disable max-len */
import Row from "./Row"
import Group from "./Group"
import Page from "./Page"
import options from "options"
import icons from "lib/icons"

const {
    autotheme: at,
    font,
    theme,
    bar: b,
    quicksettings: qs,
    osd,
} = options

const {
    dark,
    light,
    blur,
    scheme,
    padding,
    spacing,
    radius,
    shadows,
    widget,
    border,
} = theme

export default [
    Page("Theme", icons.ui.themes,
        Group("Dark Colors",
            Row({ opt: dark.bg, title: "Background", type: "color" }),
            Row({ opt: dark.fg, title: "Foreground", type: "color" }),
            Row({ opt: dark.primary.bg, title: "Primary", type: "color" }),
            Row({ opt: dark.primary.fg, title: "On Primary", type: "color" }),
            Row({ opt: dark.error.bg, title: "Error", type: "color" }),
            Row({ opt: dark.error.fg, title: "On Error", type: "color" }),
            Row({ opt: dark.widget, title: "Widget", type: "color" }),
            Row({ opt: dark.border, title: "Border", type: "color" }),
        ),
        Group("Theme",
            Row({ opt: shadows, title: "Shadows" }),
            Row({ opt: widget.opacity, title: "Widget Opacity", max: 100 }),
            Row({ opt: border.opacity, title: "Border Opacity", max: 100 }),
            Row({ opt: border.width, title: "Border Width" }),
            Row({ opt: blur, title: "Blur", note: "0 to disable", max: 70 }),
        ),
        Group("UI",
            Row({ opt: padding, title: "Padding" }),
            Row({ opt: spacing, title: "Spacing" }),
            Row({ opt: radius, title: "Roundness" }),
            Row({ opt: font.size, title: "Font Size" }),
            Row({ opt: font.name, title: "Font Name", type: "font" }),
        ),
    ),
    Page("Bar", icons.ui.toolbars,
        Group("General",
            Row({ opt: b.transparent, title: "Transparent Bar", note: "Works best on empty-ish wallpapers" }),
            Row({ opt: b.flatButtons, title: "Flat Buttons" }),
            Row({ opt: b.position, title: "Position", type: "enum", enums: ["top", "bottom"] }),
            Row({ opt: b.corners, title: "Corners" }),
        ),
        Group("Taskbar",
            Row({ opt: b.taskbar.iconSize, title: "Icon Size" }),
            Row({ opt: b.taskbar.monochrome, title: "Monochrome" }),
            Row({ opt: b.taskbar.exclusive, title: "Exclusive to workspaces" }),
        ),
        Group("Date",
            Row({ opt: b.date.format, title: "Date Format" }),
        ),
        Group("Media",
            Row({ opt: b.media.monochrome, title: "Monochrome" }),
            Row({ opt: b.media.preferred, title: "Preferred Player" }),
            Row({ opt: b.media.direction, title: "Slide Direction", type: "enum", enums: ["left", "right"] }),
            Row({ opt: b.media.format, title: "Format of the Label" }),
            Row({ opt: b.media.length, title: "Max Length of Label" }),
        ),
    ),
    Page("General", icons.ui.settings,
        Group("Quicksettings",
            Row({ opt: qs.avatar.image, title: "Avatar", type: "img" }),
            Row({ opt: qs.avatar.size, title: "Avatar Size" }),
            Row({ opt: qs.media.monochromeIcon, title: "Media Monochrome Icons" }),
            Row({ opt: qs.media.coverSize, title: "Media Cover Art Size" }),
        ),
        Group("On Screen Indicator",
            Row({ opt: osd.progress.vertical, title: "Vertical" }),
            Row({ opt: osd.progress.pack.h, title: "Horizontal Alignment", type: "enum", enums: ["start", "center", "end"] }),
            Row({ opt: osd.progress.pack.v, title: "Vertical Alignment", type: "enum", enums: ["start", "center", "end"] }),
        ),
    ),
] as const
