$font = Cantarell Regular
$clockFont = Cantarell Black
$minimalFont = Noto Sans

# GENERAL
general {
    hide_cursor = false
    ignore_empty_input = true
    text_trim = false
    fractional_scaling = 2
}

auth {
    pam {
        enabled = true
    }
    fingerprint {
        enabled = false
        ready_message = Waiting for Fingerprint
        present_message = Scanning
    }
}

# BACKGROUND
background {
    monitor =
    path = ~/.current.wall
    blur_passes = 4
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GREETINGS
label {
    monitor =
    text = Welcome!
    color = rgba(216, 222, 233, .9)
    font_size = 55
    font_family = $font
    position = 0, 320
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = $TIME
    color = rgba(216, 222, 233, .9)
    font_size = 60
    font_family = $clockFont
    position = 0, 240
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, .9)
    font_size = 19
    font_family = $font
    position = 0, 165
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = rgb(121212)
    rounding = -1
    border_size = 0
    border_color = rgba(255, 255, 255, 1)
    rotate = 0
    xray = false 
    position = 0, -140
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = rgb(ffffff)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = $font
    position = 0, -140
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2
    dots_size = .15
    dots_spacing = .3
    dots_center = true
    outer_color = rgb(151515)
    inner_color = rgba(216, 222, 233, .6)
    font_color = rgb(121212)
    fade_on_empty = false
    hide_input = false
    placeholder_text = <i><span foreground="##ffffff99"></span></i>
    check_color = rgb(204,136,34)
    fail_color = rgb(204,34,34)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -220
    halign = center
    valign = center
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] bash -c 'playerctl metadata && echo -e "    $(playerctl metadata artist)   -   $(playerctl metadata title)"' | tail -n 1
    color = rgba(255, 255, 255, 0.65)
    font_size = 14
    font_family = JetBrains Mono Nerd, $minimalFont
    position = 0, 45
    halign = center
    valign = bottom
}
