font_family JetBrainsMono NF
bold_font_name JetBrainsMono NF Bold
italic_font_name JetBrainsMono NF Italic
bold_italic_font_name JetBrainsMono NF Bold Italic
font_size 14

theme dark:Dark+, light:catppuccin-latte
background #0c090a
hide_window_decorations yes
cursor_shape block

url_color #0087bd
url_style curly
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto new ssh sftp
detect_urls yes

scrollback_lines 2000
copy_on_select yes

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
active_tab_foreground   #D1C5C2
active_tab_background   #c70039
active_tab_font_style   bold-italic
inactive_tab_foreground #938886
inactive_tab_background #312826
inactive_tab_font_style normal

enabled_layouts splits:split_axis=vertical
map ctrl+r layout_action rotate
map ctrl+n launch --location=neighbor
map ctrl+shift+k launch --location=vsplit
map ctrl+shift+j launch --location=hsplit
map ctrl+shift+l launch --location=vsplit
map ctrl+shift+h launch --location=hsplit
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down
map ctrl+h neighboring_window left
map ctrl+d close_window

map alt+h resize_window narrower 3
map alt+j resize_window shorter 3
map alt+k resize_window taller 3
map alt+l resize_window wider 3

map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down
map ctrl+f move_window_forward
map ctrl+b move_window_backward


shell_integration enabled
shell /usr/bin/fish --login --interactive

