local ls = require("luasnip")
local U = dofile(vim.fn.expand("~/snippets/tex/_utils.lua"))

local greek_letters = {
	{ trig = ";a", text = "\\alpha" },
	{ trig = ";b", text = "\\beta" },
	{ trig = ";c", text = "\\chi" },
	{ trig = ";d", text = "\\delta" },
	{ trig = ";D", text = "\\Delta" },
	{ trig = ";ep", text = "\\epsilon" },
	{ trig = ";et", text = "\\eta" },
	{ trig = ";f", text = "\\phi" },
	{ trig = ";F", text = "\\Phi" },
	{ trig = ";g", text = "\\gamma" },
	{ trig = ";G", text = "\\Gamma" },
	{ trig = ";h", text = "\\hbar" },
	{ trig = ";i", text = "\\iota" },
	{ trig = ";k", text = "\\kappa" },
	{ trig = ";l", text = "\\lambda" },
	{ trig = ";L", text = "\\Lambda" },
	{ trig = ";m", text = "\\mu" },
	{ trig = ";n", text = "\\nu" },
	{ trig = ";o", text = "\\omega" },
	{ trig = ";O", text = "\\Omega" },
	{ trig = ";pi", text = "\\pi" },
	{ trig = ";PI", text = "\\Pi" },
	{ trig = ";r", text = "\\rho" },
	{ trig = ";s", text = "\\sigma" },
	{ trig = ";S", text = "\\Sigma" },
	{ trig = ";ta", text = "\\tau" },
	{ trig = ";u", text = "\\upsilon" },
	{ trig = ";U", text = "\\Upsilon" },
	{ trig = ";th", text = "\\theta" },
	{ trig = ";T", text = "\\Theta" },
	{ trig = ";vr", text = "\\varrho" },
	{ trig = ";ve", text = "\\varepsilon" },
	{ trig = ";vp", text = "\\varphi" },
	{ trig = ";x", text = "\\xi" },
	{ trig = ";X", text = "\\Xi" },
	{ trig = ";ps", text = "\\psi" },
	{ trig = ";PS", text = "\\Psi" },
	{ trig = ";z", text = "\\zeta" },
}

ls.add_snippets("tex", U.batch_autosnippet(greek_letters))
