exec-once = uwsm-app $(python /home/c5514/.config/Ax-Shell/main.py)
exec = pgrep -x "hypridle" > /dev/null || uwsm app -- hypridle
exec = uwsm app -- swww-daemon
exec-once =  wl-paste --type text --watch cliphist store
exec-once =  wl-paste --type image --watch cliphist store

$fabricSend = fabric-cli exec ax-shell

bind = SUPER ALT, B, exec, killall ax-shell; uwsm-app $(python /home/c5514/.config/Ax-Shell/main.py) # Reload Ax-Shell
bind = SUPER, M, exec, $fabricSend 'notch.open_notch("dashboard")' # Dashboard
bind = SUPER CTRL, B, exec, $fabricSend 'notch.open_notch("bluetooth")' # Bluetooth
bind = SUPER, N, exec, $fabricSend 'notch.open_notch("kanban")' # Kanban
bind = SUPER, SPACE, exec, $fabricSend 'notch.open_notch("launcher")' # App Launcher
bind = SUPER SHIFT, T, exec, $fabricSend 'notch.open_notch("tmux")' # Tmux
bind = SUPER, V, exec, $fabricSend 'notch.open_notch("cliphist")' # Clipboard History
bind = SUPER, D, exec, $fabricSend 'notch.open_notch("tools")' # Toolbox
bind = SUPER, O, exec, $fabricSend 'notch.open_notch("overview")' # Overview
bind = SUPER, W, exec, $fabricSend 'notch.open_notch("wallpapers")' # Wallpapers
bind = SUPER SHIFT, W, exec, $fabricSend 'notch.dashboard.wallpapers.set_random_wallpaper(None, external=True)' # Random Wallpaper
bind = SUPER, A, exec, $fabricSend 'notch.open_notch("mixer")' # Audio Mixer
bind = SUPER, PERIOD, exec, $fabricSend 'notch.open_notch("emoji")' # Emoji Picker
bind = SUPER, BACKSPACE, exec, $fabricSend 'notch.open_notch("power")' # Power Menu
bind = SUPER, C, exec, $fabricSend 'notch.dashboard.widgets.buttons.caffeine_button.toggle_inhibit(external=True)' # Toggle Caffeine
bind = SUPER SHIFT, B, exec, $fabricSend 'app.set_css()' # Reload CSS
bind = SUPER CTRL ALT, B, exec, killall ax-shell; uwsm-app $(GTK_DEBUG=interactive python /home/c5514/.config/Ax-Shell/main.py) # Restart with inspector

# Wallpapers directory: /home/c5514/Pictures/Wallpapers

source = /home/c5514/.config/Ax-Shell/config/hypr/colors.conf

layerrule = noanim, fabric

exec = cp $wallpaper ~/.current.wall

general {
    col.active_border = rgb($primary)
    col.inactive_border = rgb($surface)
    gaps_in = 3
    gaps_out = 4
    border_size = 4
    layout = dwindle
}
