$wallpaper = /home/c5514/Pictures/Wallpapers/olly-moss-firewatch-red.jpg
$background = 19120c
$foreground = eee0d5

$primary = fbba73
$secondary = e0c1a3
$tertiary = becc9b
$surface = 19120c
$surface_bright = 403830
$outline = 9d8e81
$error = ff5945

$shadow = 000000

$red = ffb595
$green = b7d085
$yellow = dec56e
$blue = cebdfe
$magenta = fcb0d5
$cyan = 84d5c4
$white = 82d3e0
$red_dim = ff6e2f
$green_dim = 89ad42
$yellow_dim = bb9b2b
$blue_dim = 8359fc
$magenta_dim = f84ea1
$cyan_dim = 3eb59c
